baseURL = 'https://ashraful.eu/'
languageCode = 'en-us'
title = "Ashraful's Space"
theme = 'maverick'
paginate = 3

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Ashraful's digital garden on the world wide web. Interesting thoughts, opinions and knowledges are shared here sometimes."
  author = 'Ashraful Islam'

  [params.comments]
    enabled = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = -150

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = true
    style = 'nonokaidark'
    tabWidth = 2

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
